import type { ReportDictionary } from "./types";

export const en: ReportDictionary = {
  reportTitle: "Personal Vector Profile",
  reportSubtitle: "Comprehensive Candidate Assessment",
  confidential: "CONFIDENTIAL",
  preparedFor: "Prepared for",
  candidateLabel: "Candidate",
  positionLabel: "Position",
  departmentLabel: "Department",
  dateLabel: "Assessment Date",
  versionLabel: "Report Version",
  pageLabel: "p.",

  executiveSummary: "Executive Summary",
  overallRecommendation: "Overall Recommendation",
  overallScore: "Overall Score",
  recommendedRole: "Recommended Role",
  secondaryRole: "Secondary Role",

  discSection: "DISC Behavioral Profile",
  discOverall: "DISC Overall Score",
  discProfile: "Profile",
  discSJT: "Situational Judgment (SJT)",
  discBand: "DISC Band",
  discScales: "Scales",
  discValidity: "Validity",
  discConsistency: "Consistency",

  zimaSection: "ZIMA Role-Fit Analysis",
  zimaFitScore: "Fit Score",
  zimaPrimaryRole: "Primary Role",
  zimaSecondaryRole: "Secondary Role",
  zimaDimensions: "Dimensions",
  zimaRedFlags: "Red Flags",
  zimaEnvironment: "Environment & Conditions",
  zimaTraining: "Training Recommendations",

  ritchieSection: "Ritchie–Martin Motivational Profile",
  ritchieTopMotivators: "Top Motivators",
  ritchieBottomMotivators: "Lowest Motivators",
  ritchieRoleFit: "Role Fit",
  ritchieScales: "Motivation Scales",

  strengthsSection: "Strengths",
  risksSection: "Risk Factors",
  managementSection: "Management Recommendations",
  interviewSection: "Interview Focus Questions",
  retentionSection: "Retention Risks",
  finalSection: "Final Hiring Recommendation",

  bands: {
    strong_hire: "Strong Hire",
    recommended: "Recommended",
    conditional: "Conditional",
    not_recommended: "Not Recommended",
  },

  discBands: {
    strong_shortlist: "Strong Shortlist",
    conditional: "Conditional",
    high_risk: "High Risk",
  },

  roleFitLabels: {
    strong: "Strong",
    moderate: "Moderate",
    weak: "Weak",
  },

  roleLabels: {
    full_cycle: "Full-Cycle Account Executive",
    hunter: "New Business Hunter",
    consultative: "Consultative / Solution Seller",
    team_lead: "Sales Team Lead",
  },

  discScaleLabels: {
    D: "Dominance",
    I: "Influence",
    S: "Steadiness",
    C: "Compliance",
    K: "Control",
  },

  ritchieScaleLabels: {
    INC: "Incentive",   REC: "Recognition",  ACH: "Achievement",
    POW: "Power",       VAR: "Variety",      AUT: "Autonomy",
    STR: "Structure",   REL: "Relationships", VAL: "Values",
    DEV: "Development", SEC: "Security",      DRI: "Drive",
  },

  zimaDimensionLabels: {
    pace: "Pace",              autonomy: "Autonomy",
    collaboration: "Collaboration", risk: "Risk Tolerance",
    innovation: "Innovation",  client_focus: "Client Focus",
    process: "Process",        resilience: "Resilience",
    ambiguity: "Ambiguity Tolerance", growth: "Growth",
  },

  severityLabels: { warning: "Warning", critical: "Critical" },
  validLabel: "Valid",
  invalidLabel: "Invalid",
  consistentLabel: "Consistent",
  inconsistentLabel: "Inconsistent",

  generatedBy: "Generated by ZIMA Dubai Vector Profile",
  disclaimer: "This report is confidential and intended for internal use only. Assessment results are advisory and should be considered alongside interview outcomes and other candidate data.",
};
