// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//  PDF Report Copy — English
//
//  All static and semi-static text blocks for the "Personal Vector
//  Profile" PDF report. The PDF generator pulls from this file so
//  that no runtime copy improvisation is needed.
//
//  Brand: ZIMA Dubai Vector Profile / Personal Vector Profile
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

import type { PDFCopyDictionary } from "./reportSectionSchema";

export const pdfCopyEN: PDFCopyDictionary = {
  lang: "en",

  // ─── Meta Copy ──────────────────────────────────────────────────

  meta: {
    coverTitle: "Personal Vector Profile",
    coverSubtitle: "Comprehensive Candidate Assessment Report",
    brandLine: "ZIMA DUBAI",
    confidentialStamp: "CONFIDENTIAL — FOR INTERNAL USE ONLY",
    reportIntro:
      "This report presents the results of a structured, multi-dimensional assessment designed to evaluate the candidate's fit for a sales role within the ZIMA Dubai organisation. The assessment combines behavioural analysis (DISC), motivational profiling (Ritchie–Martin), and organisational environment alignment (ZIMA Role-Fit) to provide an integrated hiring recommendation.",

    generatedOnLabel: "Generated on",
    reportVersionLabel: "Report version",
    targetRoleLabel: "Target role",
    responsibleHRLabel: "Responsible HR",
    overallBandLabel: "Overall band",
    finalRecommendationLabel: "Final recommendation",
    overallScoreLabel: "Overall score",
    candidateLabel: "Candidate",
    positionLabel: "Position",
    departmentLabel: "Department",
    assessmentDateLabel: "Assessment date",
    pageLabel: "p.",

    validityLabel: "Response validity",
    consistencyLabel: "Response consistency",
    validCleanLabel: "Valid — no concerns",
    validCautionLabel: "Minor validity flags",
    validRiskLabel: "Significant validity concerns",
    consistentCleanLabel: "Consistent — internally coherent",
    consistentCautionLabel: "Minor inconsistencies detected",
    consistentRiskLabel: "Significant inconsistencies detected",

    roleFitStrongLabel: "Strong fit",
    roleFitModerateLabel: "Moderate fit",
    roleFitWeakLabel: "Weak fit",

    footerDisclaimer:
      "This report is confidential and intended solely for internal decision-making within the hiring organisation. Assessment results are advisory in nature and should be considered alongside structured interview outcomes, reference checks, and other candidate data. No hiring decision should be made based on this assessment alone. The assessment methodology measures self-reported behavioural tendencies and motivational preferences — it does not measure ability, intelligence, or character.",

    footerGenerated: "Generated by ZIMA Dubai Vector Profile Assessment System",
  },

  // ─── Chart & Table Microcopy ────────────────────────────────────

  charts: {
    scoreAxisLabel: "Score (0–100)",
    scaleAxisLabel: "Scale",
    dimensionAxisLabel: "Dimension",
    roleFitAxisLabel: "Role fit score",
    outOf100: "/100",
    highLabel: "High",
    mediumLabel: "Medium",
    lowLabel: "Low",
    thresholdLineLabel: "Threshold",
    noDataLabel: "No data available",
    topMotivatorsLabel: "Top motivators",
    bottomMotivatorsLabel: "Lowest motivators",
    criticalGapLabel: "Critical gap",
    redFlagLabel: "Red flag",
    warningLabel: "Warning",
    criticalLabel: "Critical",
  },

  // ─── Section Copy Blocks ────────────────────────────────────────

  sections: {
    executiveSummary: {
      heading: "Executive Summary",
      intro:
        "The following summary presents the candidate's integrated assessment results across three evaluation dimensions: behavioural competence, motivational alignment, and organisational environment fit. The overall score, recommended role, and hiring band reflect the combined output of all three assessment blocks.",
      helperNote:
        "Scores are normalised to a 0–100 scale. The overall score is a weighted composite: DISC behavioural (35%), Ritchie–Martin motivational fit (30%), and ZIMA environment alignment (35%).",
    },

    discBehavioral: {
      heading: "DISC Behavioral Profile",
      intro:
        "The DISC assessment measures four core behavioural dimensions relevant to sales performance: Dominance (D), Influence (I), Steadiness (S), and Compliance (C), supplemented by a social desirability control scale (K) and ten situational judgment scenarios (SJT). Together, these provide a reliable picture of how the candidate is likely to behave in sales-critical situations.",
      helperNote:
        "The DISC band is determined by a weighted formula (0.20D + 0.20I + 0.15S + 0.15C + 0.10K + 0.20SJT) with threshold checks on individual scales. Validity and consistency metrics indicate the reliability of the candidate's self-report.",
    },

    zimaRoleFit: {
      heading: "ZIMA Role-Fit Analysis",
      intro:
        "The ZIMA Role-Fit block evaluates the candidate's alignment with the specific operating environment and role demands at ZIMA Dubai. Ten work-style dimensions are measured and compared against role-specific weight profiles for four sales positions. The result indicates which role the candidate is naturally suited for and where environmental friction is likely.",
      helperNote:
        "Dimension scores below 40 or above 80 are flagged for review — extreme scores in either direction can signal both strengths and risks depending on the target role context.",
    },

    ritchieMotivational: {
      heading: "Ritchie–Martin Motivational Profile",
      intro:
        "The Ritchie–Martin assessment maps twelve motivational drivers that influence sustained performance, engagement, and retention in professional sales roles. Understanding what energises and what demotivates a candidate is essential for designing effective management strategies and predicting long-term fit.",
      helperNote:
        "Role-fit scores compare the candidate's motivational profile against empirically validated ideal profiles for each sales role. Critical gaps indicate scales where the candidate falls below the minimum threshold for that role.",
    },

    strengths: {
      heading: "Core Strengths",
      intro:
        "The following strengths were identified through the integrated analysis of all three assessment blocks. These represent the candidate's most reliable performance assets — the behaviours, motivations, and environmental alignments most likely to produce consistent positive outcomes in the recommended role.",
    },

    risks: {
      heading: "Risk Factors",
      intro:
        "The following risk factors were identified across the assessment. Each represents an area where the candidate's profile deviates from the ideal in a way that may impact performance, integration, or retention. Risks are not disqualifiers — they are data points for informed decision-making.",
      helperNote:
        "Risk factors should be validated through structured behavioural interview questions before being used to inform a hiring decision.",
    },

    managementRecommendations: {
      heading: "Management Recommendations",
      intro:
        "Based on the candidate's behavioural and motivational profile, the following management approach is recommended to maximise performance and engagement. These recommendations are designed to help the direct manager adapt their style to the candidate's natural preferences.",
    },

    interviewFocus: {
      heading: "Interview Focus Questions",
      intro:
        "The following questions are designed to probe specific areas where the assessment data requires real-world validation. Each question targets a gap, risk, or ambiguity identified in the candidate's profile that self-report data alone cannot resolve.",
      helperNote:
        "Use behavioural event interviewing (BEI) technique: ask for specific past examples, probe for context, actions, and outcomes. Avoid hypothetical questions.",
    },

    retentionRisks: {
      heading: "Retention Risk Indicators",
      intro:
        "The following indicators suggest conditions under which the candidate may disengage or seek opportunities elsewhere. These are not predictions — they are motivational patterns that, if not actively managed, increase the probability of turnover.",
    },

    finalRecommendation: {
      heading: "Final Hiring Recommendation",
      intro:
        "The recommendation below integrates all assessment data into a single, actionable hiring guidance. It reflects the overall score, band assignment, identified strengths and risks, role-fit analysis, and environmental alignment.",
      helperNote:
        "This assessment is one input into the hiring decision. It should be weighed alongside interview performance, reference checks, portfolio review, and other role-specific evaluation methods. No single assessment should be the sole basis for a hiring or rejection decision.",
    },
  },
};
